/**
 * Alternate wordings for pattern instructions.
 * Worksheets do not print these above each question. The section directions
 * state a shared task once, and a repeated task prompt is shown once for its group.
 */
const STEMS: Record<string, readonly string[]> = {
  "noun-proper": ["Choose the proper noun.", "Which choice is a proper noun?"],
  "noun-abstract": ["Choose the abstract noun.", "Which choice names an idea or feeling?"],
  "noun-collective": ["Choose the collective noun.", "Which word names a group as one unit?"],
  "noun-label": ["Label the italicized noun.", "Which label fits the italicized noun?"],
  "noun-two-abstract": ["Write both abstract nouns.", "List the two abstract nouns."],
  "pronoun-spot": ["Choose the pronoun.", "Which word is used as a pronoun?"],
  "pronoun-type": ["Name the type of the italicized pronoun.", "Which pronoun type is italicized?"],
  "pronoun-replace": ["Replace the repeated noun with a pronoun.", "Rewrite the second sentence using a pronoun for the repeated noun."],
  "pronoun-case-preview": ["Name the type of the italicized pronoun.", "Which type fits the italicized pronoun?"],
  "pronoun-type-more": ["Name the type of the italicized pronoun.", "Which pronoun type is shown?"],
  "verb-kind": ["Label the italicized verb.", "Is the italicized verb action, linking, or helping?"],
  "verb-transitive": ["Is the italicized verb transitive or intransitive?", "Choose transitive or intransitive for the italicized verb."],
  "verb-helping-write": ["Write only the helping verb.", "Which word is the helping verb?"],
  "verb-kind-more": ["Label the italicized verb.", "Is the italicized verb action, linking, or helping?"],
  "adj-adv-choice": ["Choose the word that completes the sentence correctly.", "Which form, adjective or adverb, fits the sentence?"],
  "adj-adv-degree": ["Name the degree of the italicized word.", "Is the italicized form positive, comparative, or superlative?"],
  "adj-or-adv-label": ["Is the italicized word an adjective or an adverb?", "Label the italicized word as an adjective or an adverb."],
  "adj-adv-more": ["Choose the adjective or adverb that fits.", "Which form completes the sentence?"],
  "prep-word": ["Choose the preposition.", "Which word is the preposition?"],
  "prep-phrase": ["Choose the prepositional phrase.", "Which group of words is a prepositional phrase?"],
  "prep-complete": ["Choose the preposition that fits.", "Which preposition completes the sentence?"],
  "prep-vs-conj": ["Is the italicized word a preposition or a subordinating conjunction?", "Label the italicized word."],
  "prep-more": ["Choose the preposition.", "Which word is a preposition?"],
  "conj-type": ["Name the kind of conjunction.", "Is the italicized conjunction coordinating, subordinating, or correlative?"],
  "conj-relationship": ["Choose the conjunction that fits the relationship.", "Which conjunction matches the hint in parentheses?"],
  "conj-type-more": ["Name the kind of conjunction.", "Which conjunction type is italicized?"],
  "conj-fit-more": ["Choose the conjunction that fits.", "Which conjunction shows the relationship in parentheses?"],
  "interjection-spot": ["Choose the interjection.", "Which word is an interjection?"],
  "interjection-punct": ["Choose the punctuation that follows the interjection.", "How should the interjection be punctuated?"],
  "interjection-fit": ["Choose the interjection that fits.", "Which interjection matches the situation?"],
  "interjection-rewrite": ["Punctuate the interjection.", "Rewrite the sentence with the interjection punctuated correctly."],
  "interjection-more": ["Choose the interjection.", "Which word is an interjection?"],
  "sva-basic": ["Choose the verb that agrees with the subject.", "Which verb in parentheses agrees with the subject?"],
  "sva-intervening": ["Choose the verb that agrees with the subject.", "Ignore the interrupting phrase and choose the agreeing verb."],
  "sva-indefinite": ["Choose the verb that agrees with the subject.", "Which verb agrees with the indefinite pronoun?"],
  "sva-compound-and": ["Choose the verb that agrees with the subject.", "Which verb agrees with the compound subject?"],
  "sva-or-nor": ["Choose the verb that agrees with the nearer subject.", "Which verb agrees in this either/or or neither/nor sentence?"],
  "sva-there": ["Choose the verb that agrees with the real subject.", "Which verb agrees with the subject that follows it?"],
  "sva-collective": ["Choose the verb that agrees with the collective noun.", "Which verb fits when the group acts as one unit?"],
  "sva-special": ["Choose the verb that agrees with the subject.", "Which verb agrees?"],
  "sva-edit": ["Edit the passage so the verbs agree.", "Rewrite the passage with verbs that agree with their subjects."],
  "sva-more-intervening": ["Choose the verb that agrees with the subject.", "Which verb agrees once you find the real subject?"],
  "antecedent-choice": ["Choose the pronoun that agrees with its antecedent.", "Which pronoun matches the antecedent in number?"],
  "antecedent-rewrite": ["Make the pronoun agree with its antecedent.", "Rewrite the sentence so the pronoun agrees."],
  "antecedent-more": ["Choose the agreeing pronoun.", "Which pronoun matches the antecedent?"],
  "case-i-me": ["Choose the pronoun case that fits.", "Should the pronoun be subjective or objective?"],
  "case-who": ["Choose the pronoun that fits.", "Which pronoun fits the job it does in the sentence?"],
  "tense-choice": ["Choose the verb that keeps the tense consistent.", "Which verb matches the time already established?"],
  "tense-rewrite": ["Make the verb tense consistent.", "Rewrite the sentence so the tense does not shift without a reason."],
  "tense-choice-more": ["Choose the verb that keeps the tense steady.", "Which verb form matches the established time?"],
  "tense-rewrite-more": ["Rewrite the sentence with consistent tense.", "Correct the tense shift."],
  "mood-identify": ["Name the mood of the main verb.", "Is the mood indicative, imperative, or subjunctive?"],
  "mood-rewrite": ["Rewrite the sentence in the mood the meaning needs.", "Correct the verb mood."],
  "mood-more": ["Name the mood.", "Which mood is the main verb?"],
  "voice-to-passive": [
    "Name the voice, then rewrite the sentence in the opposite voice. Keep the tense the same.",
    "Say whether the sentence is active or passive, and rewrite it in the other voice without changing the tense.",
  ],
  "voice-to-active": [
    "Identify the voice of the sentence, then rewrite it in the opposite voice. Keep the tense the same.",
    "Label the sentence active or passive, then rewrite it in the other voice. Do not change the tense.",
  ],
  "parallel-series": ["Make the series parallel.", "Rewrite the sentence so the series uses matching forms."],
  "parallel-choice": ["Choose the parallel revision.", "Which revision makes the forms match?"],
  "parallel-correlative": ["Make the correlative pair parallel.", "Rewrite the sentence so both sides of the pair match."],
  "clause-which": ["Choose the dependent clause.", "Which group of words is a dependent clause?"],
  "clause-label": ["Label the italicized clause.", "Is the italicized group independent or dependent?"],
  "clause-more": ["Choose the dependent clause.", "Which word group cannot stand alone?"],
  "sentence-types-core": ["Name the sentence type.", "Is the sentence simple, compound, or complex?"],
  "sentence-types-upper": ["Name the sentence type.", "Classify the sentence."],
  "sentence-types-more": ["Name the sentence type.", "Classify this sentence."],
  "phrase-kind": ["Name the kind of phrase that is italicized.", "Which phrase type is italicized?"],
  "phrase-more": ["Name the italicized phrase type.", "Which kind of phrase is italicized?"],
  "fragment-identify": ["Is the word group a fragment or a complete sentence?", "Choose fragment or complete sentence."],
  "fragment-repair": ["Turn the fragment into a complete sentence.", "Rewrite the fragment so it can stand alone."],
  "fragment-identify-more": ["Choose fragment or complete sentence.", "Is this a fragment or a complete sentence?"],
  "fragment-repair-more": ["Rewrite the fragment as a sentence.", "Complete the fragment."],
  "runon-identify": ["Choose the comma splice.", "Which sentence is a comma splice?"],
  "runon-period": ["Break the run-on into two sentences.", "Rewrite the run-on as two sentences."],
  "runon-semi": ["Join the clauses with a semicolon.", "Rewrite the run-on with a semicolon and no conjunction."],
  "runon-and": ["Join the clauses with a comma and and.", "Rewrite the run-on as a compound sentence with and."],
  "modifier-dangling": ["Give the opening modifier a clear subject.", "Rewrite the sentence so the modifier describes the right word."],
  "modifier-misplaced": ["Move the modifier next to the word it describes.", "Rewrite the sentence so the modifier is placed clearly."],
  "combining-basic": ["Combine the sentences as directed.", "Follow the directions and combine the sentences."],
  "combining-advanced": ["Combine the sentences as directed.", "Follow the directions and combine the sentences."],
  "end-mark": ["Choose the end mark.", "Which punctuation mark should end the sentence?"],
  "comma-list": ["Add the commas a series needs, including the Oxford comma.", "Rewrite the list with commas, including the comma before and."],
  "comma-intro": ["Add a comma after the introductory element.", "Rewrite the sentence with the introductory comma."],
  "comma-compound": ["Add a comma before the conjunction only if the sentence needs one.", "Fix the comma before the coordinating conjunction."],
  "comma-nonrestrictive": ["Add commas only where they are needed.", "Rewrite the sentence, or write correct if it needs no comma."],
  "comma-appositive": ["Set off a nonrestrictive appositive with commas.", "Add appositive commas, or write correct if none are needed."],
  "comma-trap": ["Add commas only where they are needed.", "Rewrite the sentence, or write correct if it is already punctuated."],
  "comma-address": ["Set off a name used in direct address.", "Add the comma or commas that direct address needs."],
  "comma-place-date": ["Add the commas a date or place name needs.", "Rewrite the sentence with commas in the date or place."],
  "semi-colon-choice": ["Choose the punctuation that belongs in the blank.", "Which mark belongs in the blank?"],
  "semi-more": ["Choose the punctuation that belongs in the blank.", "Which mark fits the blank?"],
  "apostrophe-possession": ["Choose the possessive form that fits the hint.", "Which form shows possession correctly?"],
  "apostrophe-contraction": ["Replace the words with a contraction.", "Rewrite the sentence using a contraction."],
  "apostrophe-more": ["Choose the correct possessive form.", "Which form shows possession?"],
  "apostrophe-contraction-more": ["Rewrite the sentence with a contraction.", "Contract the words that can form a contraction."],
  "quote-basic": ["Punctuate the dialogue.", "Rewrite the sentence with correct quotation marks."],
  "quote-advanced": ["Punctuate the quotation.", "Rewrite the sentence with correct quotation marks."],
  "hyphen-choice": ["Choose the sentence that is punctuated correctly.", "Which sentence uses the hyphen, dash, or parentheses correctly?"],
  "hyphen-more": ["Choose the correctly punctuated sentence.", "Which sentence uses the hyphen correctly?"],
  "titles-punctuate": ["Punctuate the title. Use *asterisks* for italics.", "Rewrite the sentence with the title punctuated correctly."],
  "titles-more": ["Punctuate the title, using *asterisks* for italics.", "Rewrite the sentence so the title is punctuated correctly."],
  "confused-words": ["Choose the word that completes the sentence.", "Which word fits the sentence?"],
  "double-negative": ["Rewrite the sentence with only one negative.", "Remove the double negative without changing the meaning."],
  "compare-choice": ["Choose the comparative or superlative that fits.", "Which form of comparison fits?"],
  "compare-double": ["Rewrite the sentence so the comparison is grammatical.", "Fix the comparison."],
  "compare-more": ["Choose the form of comparison that fits.", "Which comparative or superlative completes the sentence?"],
  "compare-fix-more": ["Fix the comparison.", "Rewrite the sentence so the comparison follows the rule."],
  capitalization: ["Capitalize the sentence correctly.", "Rewrite the sentence with standard capitalization."],
  "capitalization-clean": ["Capitalize the sentence correctly.", "Rewrite the sentence with standard capitalization."],
  "capitalization-more": ["Rewrite the sentence with correct capitalization.", "Capitalize every word that needs a capital letter."],
  "numbers-small": ["Rewrite the sentence using the classroom number rules.", "Apply the number rules to the sentence."],
  "numbers-abbrev": ["Spell out the abbreviations that do not belong in formal prose.", "Rewrite the sentence so the abbreviations fit formal prose."],
  "numbers-more": ["Apply the classroom number rules.", "Rewrite the numbers so they follow the classroom rules."],
  "register-rewrite": ["Rewrite the sentence in formal academic language.", "Make the sentence formal without changing the meaning."],
  "register-choice": ["Choose the most formal wording.", "Which choice is the most formal?"],
  "register-more": ["Rewrite the sentence in a formal register.", "Replace the casual wording with formal wording."],
  "register-choice-more": ["Choose the most formal option.", "Which wording belongs in formal writing?"],
};

export function stemsFor(id: string): readonly string[] {
  return STEMS[id] ?? [];
}
