import { NAMES } from "./names";
import { BAND, choicePattern, pattern, revisionPattern, type Pattern } from "./engine";
import type { Difficulty } from "../types";

const dev: Difficulty[] = ["developing"];
const prof: Difficulty[] = ["proficient"];
const adv: Difficulty[] = ["advanced"];
const all = [...dev, ...prof, ...adv];
const upper = [...prof, ...adv];

type WordItem = {
  levels: Difficulty[];
  stimulus: string;
  answer: string;
  distractors: string[];
  explanation: string;
};

function word(
  levels: Difficulty[],
  stimulus: string,
  answer: string,
  distractors: string[],
  explanation: string,
): WordItem {
  return { levels, stimulus, answer, distractors, explanation };
}

const WORDS: WordItem[] = [
  word(all, "The rain will ____ our plans for the field trip.", "affect", ["effect"], "Affect is the verb meaning to influence. Effect is usually a noun meaning result."),
  word(all, "The ____ of the new rule was immediate.", "effect", ["affect"], "Effect is the noun meaning result."),
  word(all, "Staying up late can ____ your score on the quiz.", "affect", ["effect"], "Affect is the verb."),
  word(all, "One ____ of practice is a steadier bow arm.", "effect", ["affect"], "Effect is the noun."),
  word(all, "The microscope lost ____ lens cap.", "its", ["it's"], "Its is the possessive pronoun. It's means it is."),
  word(all, "____ too late to start a new trial.", "It's", ["Its"], "It's means it is."),
  word(all, "The tree dropped ____ leaves.", "its", ["it's"], "Its shows possession."),
  word(all, "____ going to rain before the match.", "It's", ["Its"], "It's means it is."),
  word(all, "The students left ____ posters in the hall.", "their", ["there", "they're"], "Their shows possession."),
  word(all, "____ is a quiet room beside the library.", "There", ["Their", "They're"], "There points to a place or introduces the sentence."),
  word(all, "____ waiting for the late bus.", "They're", ["Their", "There"], "They're means they are."),
  word(all, "Put the beakers ____ on the cart.", "there", ["their", "they're"], "There means in that place."),
  word(all, "____ project is due Friday.", "Your", ["You're"], "Your is possessive."),
  word(all, "____ on the cue after the solo.", "You're", ["Your"], "You're means you are."),
  word(all, "Is this ____ folder?", "your", ["you're"], "Your is possessive."),
  word(all, "____ the first group to present.", "You're", ["Your"], "You're means you are."),
  word(all, "We need ____ more beakers, not one.", "two", ["to", "too"], "Two is the number."),
  word(all, "This soup is ____ salty.", "too", ["to", "two"], "Too means excessively."),
  word(all, "Walk ____ the greenhouse after class.", "to", ["too", "two"], "To introduces the phrase."),
  word(all, "Maya wants to go, ____.", "too", ["to", "two"], "Too means also."),
  word(all, "Finish the graph, and ____ write the caption.", "then", ["than"], "Then shows time order."),
  word(all, "This draft is clearer ____ the first one.", "than", ["then"], "Than is used in comparisons."),
  word(all, "We rehearsed, and ____ we set the cues.", "then", ["than"], "Then means next."),
  word(all, "A ruler is longer ____ a pencil.", "than", ["then"], "Than completes the comparison."),
  word(upper, "Please ____ the award on behalf of the club.", "accept", ["except"], "Accept means to receive. Except means excluding."),
  word(upper, "Everyone ____ Maya has a pass.", "except", ["accept"], "Except means excluding."),
  word(upper, "The director will ____ no late entries.", "accept", ["except"], "Accept means to receive or allow."),
  word(upper, "The lab is open every day ____ Sunday.", "except", ["accept"], "Except means other than."),
  word(upper, "____ students joined the choir this year.", "Fewer", ["Less"], "Fewer is for countable nouns such as students."),
  word(upper, "There is ____ time than we expected.", "less", ["fewer"], "Less is for noncount nouns such as time."),
  word(upper, "We have ____ beakers than yesterday.", "fewer", ["less"], "Beakers can be counted, so use fewer."),
  word(upper, "The new pump uses ____ water.", "less", ["fewer"], "Water is noncount here, so use less."),
  word(upper, "The choice is ____ the two endings.", "between", ["among"], "Between is for two."),
  word(upper, "Share the copies ____ the four partners.", "among", ["between"], "Among is for three or more."),
  word(upper, "Stand ____ Maya and Luis.", "between", ["among"], "Between is for two people."),
  word(upper, "The rumor spread ____ the cast.", "among", ["between"], "The cast is a group of more than two."),
  word(upper, "The ____ of the school signed the form.", "principal", ["principle"], "Principal is the person who leads a school. Principle is a rule."),
  word(upper, "Fairness is the guiding ____.", "principle", ["principal"], "Principle means a basic rule or belief."),
  word(upper, "The ____ reason for the delay was the weather.", "principal", ["principle"], "Principal can mean main or most important."),
  word(upper, "We memorized the ____ of conservation of mass.", "principle", ["principal"], "A scientific rule is a principle."),
  word(upper, "____ goggles are on the counter?", "Whose", ["Who's"], "Whose is possessive."),
  word(upper, "____ ready for the cue?", "Who's", ["Whose"], "Who's means who is."),
  word(upper, "Don't ____ the lens cap.", "lose", ["loose"], "Lose means to misplace. Loose means not tight."),
  word(upper, "The latch is too ____.", "loose", ["lose"], "Loose means not firmly fastened."),
  word(adv, "Yesterday I ____ on the couch for an hour.", "lay", ["laid", "lie"], "The past tense of lie, meaning to recline, is lay."),
  word(adv, "Yesterday I ____ the book on the desk.", "laid", ["lay", "lain"], "The past tense of lay, meaning to put something down, is laid."),
  word(adv, "Please ____ the posters on the table.", "lay", ["lie", "laid"], "Lay means to put something down. It needs an object, posters."),
  word(adv, "The dust has ____ on the backdrop for a week.", "lain", ["laid", "lay"], "Lain is the past participle of lie, meaning to recline."),
  word(adv, "The ending ____ that the narrator is unreliable.", "implies", ["infers"], "A text implies. A reader infers."),
  word(adv, "From the ending, we ____ that the narrator is unreliable.", "infer", ["imply"], "Readers infer a conclusion from evidence."),
  word(adv, "The poem makes an ____ to the myth of Icarus.", "allusion", ["illusion"], "An allusion is an indirect reference. An illusion is a false appearance."),
  word(adv, "The mirror created an ____ of a longer hallway.", "illusion", ["allusion"], "An illusion is something that appears real but is not."),
  word(adv, "The survey was designed to ____ honest answers.", "elicit", ["illicit"], "Elicit means to draw out. Illicit means illegal."),
  word(adv, "The film depicts an ____ market.", "illicit", ["elicit"], "Illicit means forbidden by law."),
  word(adv, "Please be ____ about the surprise rehearsal.", "discreet", ["discrete"], "Discreet means tactful. Discrete means separate."),
  word(adv, "The data fall into three ____ groups.", "discrete", ["discreet"], "Discrete means individually separate."),
  word(adv, "An ____ storm warning scrolled across the screen.", "imminent", ["eminent"], "Imminent means about to happen."),
  word(adv, "The ____ biologist visited the lab.", "eminent", ["imminent"], "Eminent means distinguished."),
  word(adv, "____ the article in your bibliography.", "Cite", ["Site", "Sight"], "Cite means to quote or credit a source."),
  word(adv, "The dig ____ is closed to visitors.", "site", ["cite", "sight"], "A site is a place."),
  word(adv, "The mural was a welcome ____.", "sight", ["site", "cite"], "Sight means something seen."),
  word(adv, "A short introduction should ____ the results.", "precede", ["proceed"], "Precede means to come before."),
  word(adv, "After the warning, we may ____ with the trial.", "proceed", ["precede"], "Proceed means to go forward."),
  word(adv, "The compliment was a nice ____ to her speech.", "complement", ["compliment"], "A complement completes something. A compliment is praise."),
  word(adv, "She received a sincere ____ after the solo.", "compliment", ["complement"], "A compliment is an expression of praise."),
  word(adv, "The library is ____ down the hall.", "farther", ["further"], "Farther refers to physical distance."),
  word(adv, "We need ____ evidence before we publish.", "further", ["farther"], "Further refers to additional degree or amount, not distance."),
  word(adv, "The state ____ meets on Thursday.", "capitol", ["capital"], "Capitol is the building where a legislature meets."),
  word(adv, "Begin the sentence with a ____ letter.", "capital", ["capitol"], "Capital describes an uppercase letter."),
  word(adv, "Save room for ____.", "dessert", ["desert"], "Dessert is the sweet course."),
  word(adv, "The class crossed a model of the ____.", "desert", ["dessert"], "A desert is dry land."),
  word(all, "____ did you ask for help?", "Whom", ["Who"], "Whom is the object of ask. You is the subject."),
  word(all, "____ left the lights on?", "Who", ["Whom"], "Who is the subject of left."),
  word(upper, "The advice will ____ that the units are consistent.", "ensure", ["insure", "assure"], "Ensure means to make certain. Insure refers to insurance. Assure means to tell someone confidently."),
  word(upper, "I can ____ you that the samples are labeled.", "assure", ["ensure", "insure"], "Assure means to give a person confidence."),
  word(adv, "Please ____ the cast before the audition.", "counsel", ["council"], "Counsel means to advise. A council is a group of people."),
  word(adv, "The student ____ meets on Thursday.", "council", ["counsel"], "A council is a group that meets. Counsel means advice or to advise."),
];

const MORE_WORDS: WordItem[] = [
  word(all, "A late bus will ____ the start of rehearsal.", "affect", ["effect"], "Affect is the verb meaning to influence."),
  word(all, "One ____ of the new seating chart was a quieter room.", "effect", ["affect"], "Effect is the noun meaning a result."),
  word(all, "Dust on the lens can ____ the focus.", "affect", ["effect"], "Affect is the verb. The dust influences the focus."),
  word(all, "The main ____ of daily practice is confidence.", "effect", ["affect"], "Effect is the noun meaning result."),
  word(all, "Will this schedule change ____ the deadline?", "affect", ["effect"], "Affect is the verb meaning to change or influence."),
  word(all, "We measured the ____ of extra light on the plants.", "effect", ["affect"], "Effect is the noun. The sentence names a result that was measured."),
  word(all, "Skipping breakfast can ____ your energy in first period.", "affect", ["effect"], "Affect is the verb meaning to influence."),
  word(all, "A welcome ____ of the new rule was shorter lines.", "effect", ["affect"], "Effect is the noun meaning result."),
  word(all, "The school posted ____ honor roll before lunch.", "its", ["it's"], "Its is the possessive pronoun. The honor roll belongs to the school."),
  word(all, "____ almost time for the curtain.", "It's", ["Its"], "It's means it is."),
  word(all, "The committee moved ____ meeting to the library.", "its", ["it's"], "Its shows that the meeting belongs to the committee."),
  word(all, "____ the only beaker that cracked.", "It's", ["Its"], "It's means it is."),
  word(all, "The city closed ____ pool for repairs.", "its", ["it's"], "Its is possessive. The pool belongs to the city."),
  word(all, "____ hard to hear the cue from the back row.", "It's", ["Its"], "It's means it is."),
  word(all, "The club redesigned ____ logo.", "its", ["it's"], "Its is the possessive form. It's would mean it is."),
  word(all, "____ raining too hard for the picnic.", "It's", ["Its"], "It's means it is."),
  word(all, "The actors forgot ____ props backstage.", "their", ["there", "they're"], "Their shows possession. The props belong to the actors."),
  word(all, "____ going to the library after lunch.", "They're", ["Their", "There"], "They're means they are."),
  word(all, "Leave the spare gels ____ until the cue.", "there", ["their", "they're"], "There means in that place."),
  word(all, "____ posters are still wet.", "Their", ["There", "They're"], "Their is possessive and modifies posters."),
  word(all, "____ is a spare key in the top drawer.", "There", ["Their", "They're"], "There introduces the sentence. Their would show possession, and they're means they are."),
  word(all, "____ the students who built the set.", "They're", ["Their", "There"], "They're means they are."),
  word(all, "The hikers lost ____ map near the creek.", "their", ["there", "they're"], "Their shows that the map belongs to the hikers."),
  word(all, "Set the trophy ____ on the middle shelf.", "there", ["their", "they're"], "There means in that place."),
  word(all, "____ bus is the one with the open door.", "Their", ["There", "They're"], "Their is possessive and modifies bus."),
  word(all, "____ waiting in the lobby with the passes.", "They're", ["Their", "There"], "They're means they are."),
  word(all, "Bring ____ calculator to the quiz.", "your", ["you're"], "Your is possessive."),
  word(all, "____ responsible for the props tonight.", "You're", ["Your"], "You're means you are."),
  word(all, "Is ____ name on the call sheet?", "your", ["you're"], "Your is possessive and modifies name."),
  word(all, "____ going to need a hall pass.", "You're", ["Your"], "You're means you are."),
  word(all, "I liked ____ thesis more than the first draft.", "your", ["you're"], "Your is possessive and modifies thesis."),
  word(all, "____ the understudy for the second scene.", "You're", ["Your"], "You're means you are."),
  word(all, "The soup is ____ hot to serve.", "too", ["to", "two"], "Too means excessively."),
  word(all, "We need ____ more chairs in the front row.", "two", ["to", "too"], "Two is the number."),
  word(all, "The path leads ____ the ridge.", "to", ["too", "two"], "To introduces the phrase the ridge."),
  word(all, "This warm-up is ____ hard for the first day.", "too", ["to", "two"], "Too means excessively."),
  word(all, "Priya wants a part in the play, ____.", "too", ["to", "two"], "Too means also."),
  word(all, "Add ____ drops of indicator to the beaker.", "two", ["to", "too"], "Two is the number."),
  word(all, "Please carry the backdrop ____ the stage.", "to", ["too", "two"], "To introduces the destination."),
  word(all, "The hallway is ____ narrow for the set.", "too", ["to", "two"], "Too means excessively."),
  word(all, "Read the chapter, and ____ answer the questions.", "then", ["than"], "Then shows what happens next."),
  word(all, "A meter is longer ____ a yard.", "than", ["then"], "Than is used in comparisons."),
  word(all, "We ate lunch and ____ started the lab.", "then", ["than"], "Then means next or after that."),
  word(all, "This draft is stronger ____ the first one.", "than", ["then"], "Than completes the comparison."),
  word(all, "Label the samples, ____ store them on ice.", "then", ["than"], "Then shows time order."),
  word(all, "The ridge trail is steeper ____ the creek trail.", "than", ["then"], "Than is the word used to compare two trails."),
  word(all, "Wash the beakers, and ____ dry them.", "then", ["than"], "Then means next. Than would start a comparison, which this sentence does not make."),
  word(all, "This solo is shorter ____ the one we cut.", "than", ["then"], "Than introduces the comparison."),
  word(all, "____ should I ask for a visitor pass?", "Whom", ["Who"], "Whom is the object of ask. I is the subject."),
  word(all, "____ borrowed the camera from the lab?", "Who", ["Whom"], "Who is the subject of borrowed."),
  word(all, "Loud rehearsals can ____ a neighbor's evening.", "affect", ["effect"], "Affect is the verb meaning to influence."),
  word(all, "The ____ of the extra rehearsal was a cleaner finale.", "effect", ["affect"], "Effect is the noun meaning a result."),
  word(all, "The theater lost ____ spare spotlight.", "its", ["it's"], "Its is the possessive pronoun. It's would mean it is."),
  word(all, "____ time to reset the lights.", "It's", ["Its"], "It's means it is."),
  word(all, "The painters left ____ brushes in the sink.", "their", ["there", "they're"], "Their shows that the brushes belong to the painters."),
  word(all, "____ a fresh roll of tape in the shop.", "There's", ["Theirs", "They're"], "There's means there is. Theirs would show possession, and they're means they are."),
  word(all, "Don't forget ____ hall pass.", "your", ["you're"], "Your is possessive and modifies hall pass."),
  word(all, "The encore ran ____ long.", "too", ["to", "two"], "Too means excessively."),
  word(all, "____ did the director choose for the solo?", "Whom", ["Who"], "Whom is the object of choose. The director is the subject."),
  word(all, "____ left a trumpet in the band room?", "Who", ["Whom"], "Who is the subject of left."),
  word(upper, "The museum will ____ student work through Friday.", "accept", ["except"], "Accept means to receive."),
  word(upper, "The library is open every weekday ____ Friday.", "except", ["accept"], "Except means excluding."),
  word(upper, "Please ____ the package at the front desk.", "accept", ["except"], "Accept means to take or receive something offered."),
  word(upper, "Everyone ____ the understudies has a costume.", "except", ["accept"], "Except means other than."),
  word(upper, "____ riders waited after the second bus left.", "Fewer", ["Less"], "Riders can be counted, so use fewer."),
  word(upper, "The new route uses ____ fuel.", "less", ["fewer"], "Fuel is noncount here, so use less."),
  word(upper, "We collected ____ signatures than last year.", "fewer", ["less"], "Signatures can be counted, so use fewer."),
  word(upper, "There is ____ noise in this hallway.", "less", ["fewer"], "Noise is noncount here, so use less."),
  word(upper, "The difference is ____ the two endings.", "between", ["among"], "Between is for two."),
  word(upper, "Divide the copies ____ the six groups.", "among", ["between"], "Among is for three or more."),
  word(upper, "Sit ____ the window and the door.", "between", ["among"], "Between is for two places."),
  word(upper, "The prize was shared ____ the finalists.", "among", ["between"], "Finalists names a group of more than two, so use among."),
  word(upper, "The ____ postponed the assembly.", "principal", ["principle"], "Principal is the person who leads a school."),
  word(upper, "Honesty is the ____ behind the honor code.", "principle", ["principal"], "A principle is a rule or belief."),
  word(upper, "Cost was the ____ reason for the change.", "principal", ["principle"], "Principal can mean main or most important."),
  word(upper, "The lab report explains the ____ of buoyancy.", "principle", ["principal"], "A scientific rule is a principle."),
  word(upper, "____ jacket was left on the riser?", "Whose", ["Who's"], "Whose is possessive and modifies jacket."),
  word(upper, "____ conducting the warm-up today?", "Who's", ["Whose"], "Who's means who is."),
  word(upper, "Don't ____ the permission slip.", "lose", ["loose"], "Lose means to misplace. Loose means not tight."),
  word(upper, "The hinge is ____, so the door rattles.", "loose", ["lose"], "Loose means not firmly fastened."),
  word(upper, "A checklist will ____ that every sample is labeled.", "ensure", ["insure", "assure"], "Ensure means to make certain."),
  word(upper, "I can ____ the judges that the timing is accurate.", "assure", ["ensure", "insure"], "Assure means to tell a person something with confidence."),
  word(upper, "The school will ____ the instruments for the trip.", "insure", ["ensure", "assure"], "Insure means to buy insurance for something."),
  word(adv, "Last night the cat ____ on the warm stage.", "lay", ["laid", "lie"], "The past tense of lie, meaning to recline, is lay. There is no direct object."),
  word(adv, "Last night I ____ the script on the piano.", "laid", ["lay", "lain"], "The past tense of lay, meaning to put something down, is laid. Script is the direct object."),
  word(adv, "Please ____ the gels on the table.", "lay", ["lie", "laid"], "Lay means to put something down and needs an object, gels."),
  word(adv, "The costumes have ____ in the trunk all summer.", "lain", ["laid", "lay"], "Lain is the past participle of lie, meaning to rest. Trunk is not a direct object of the verb."),
  word(adv, "The caption ____ that the photo was staged.", "implies", ["infers"], "A text implies. A reader infers."),
  word(adv, "From the caption, readers ____ that the photo was staged.", "infer", ["imply"], "Readers infer a conclusion from evidence."),
  word(adv, "The title is an ____ to a Greek myth.", "allusion", ["illusion"], "An allusion is an indirect reference."),
  word(adv, "The fog created an ____ of a deeper stage.", "illusion", ["allusion"], "An illusion is a misleading appearance."),
  word(adv, "The survey questions were written to ____ honest answers.", "elicit", ["illicit"], "Elicit means to draw out."),
  word(adv, "The article describes an ____ trade in artifacts.", "illicit", ["elicit"], "Illicit means illegal."),
  word(adv, "Be ____ when you discuss the score.", "discreet", ["discrete"], "Discreet means tactful or careful."),
  word(adv, "Sort the slides into four ____ piles.", "discrete", ["discreet"], "Discrete means separate."),
  word(adv, "An ____ deadline appeared on the board.", "imminent", ["eminent"], "Imminent means about to happen."),
  word(adv, "An ____ historian spoke at the assembly.", "eminent", ["imminent"], "Eminent means distinguished."),
  word(adv, "____ the interview in your works-cited list.", "Cite", ["Site", "Sight"], "Cite means to credit a source."),
  word(adv, "The excavation ____ is closed on Sundays.", "site", ["cite", "sight"], "A site is a location."),
  word(adv, "The comet was a rare ____.", "sight", ["site", "cite"], "A sight is something seen."),
  word(adv, "A short preface should ____ the first chapter.", "precede", ["proceed"], "Precede means to come before."),
  word(adv, "After the fire drill, class may ____.", "proceed", ["precede"], "Proceed means to go forward."),
  word(adv, "The blue scarf is a ____ to the uniform.", "complement", ["compliment"], "A complement completes something else."),
  word(adv, "The review ended with a specific ____.", "compliment", ["complement"], "A compliment is praise."),
  word(adv, "The field house is ____ from the road than the gym.", "farther", ["further"], "Farther refers to physical distance."),
  word(adv, "The editor asked for ____ revision.", "further", ["farther"], "Further means additional."),
  word(adv, "The legislature meets in the ____.", "capitol", ["capital"], "A capitol is the building where a legislature meets."),
  word(adv, "Austin is the ____ of Texas.", "capital", ["capitol"], "A capital is a city that serves as a seat of government."),
  word(adv, "Save a slice of ____ for the cast party.", "dessert", ["desert"], "Dessert is the sweet course."),
  word(adv, "The diorama showed a ____ at noon.", "desert", ["dessert"], "A desert is a dry region."),
  word(adv, "The counselor can ____ seniors about the application.", "counsel", ["council"], "Counsel means to advise."),
  word(adv, "The city ____ voted to repair the bridge.", "council", ["counsel"], "A council is a group that meets to decide."),
  word(adv, "The coach's ____ was to rest before the match.", "advice", ["advise"], "Advice is the noun. Advise is the verb."),
  word(adv, "The coach will ____ the team to rest.", "advise", ["advice"], "Advise is the verb meaning to recommend."),
  word(adv, "Take a deep ____ before the first note.", "breath", ["breathe"], "Breath is the noun. Breathe is the verb."),
  word(adv, "Remember to ____ before you speak.", "breathe", ["breath"], "Breathe is the verb."),
  word(adv, "The parade ____ the school at noon.", "passed", ["past"], "Passed is the past tense of the verb pass."),
  word(adv, "We have studied this scene in the ____.", "past", ["passed"], "Past is the noun or adjective for an earlier time. Passed is the verb."),
  word(adv, "The hallway was ____ during the test.", "quiet", ["quite"], "Quiet means silent. Quite means very or completely."),
  word(adv, "The second trial was ____ different from the first.", "quite", ["quiet"], "Quite means to a considerable degree."),
  word(adv, "The ____ forced us to move the picnic indoors.", "weather", ["whether"], "Weather is rain, wind, and temperature."),
  word(adv, "We asked ____ the paint was dry.", "whether", ["weather"], "Whether introduces an indirect question."),
  word(adv, "The camera on the tripod is ____.", "stationary", ["stationery"], "Stationary means not moving."),
  word(adv, "The thank-you notes are on school ____.", "stationery", ["stationary"], "Stationery is writing paper."),
  word(adv, "Please leave ____ items in the locker.", "personal", ["personnel"], "Personal means private or belonging to one person."),
  word(adv, "The stage ____ arrive an hour early.", "personnel", ["personal"], "Personnel means the staff or the people employed."),
  word(adv, "The fable ends with a clear ____.", "moral", ["morale"], "A moral is a lesson."),
  word(adv, "A fair schedule lifted the cast's ____.", "morale", ["moral"], "Morale is confidence or spirit."),
  word(upper, "The costumes are ____ packed for the trip.", "already", ["all ready"], "Already means before now. All ready means completely prepared."),
  word(upper, "The costumes are ____ for the trip.", "all ready", ["already"], "All ready means everyone or everything is prepared."),
  word(upper, "We rehearse ____ after school.", "every day", ["everyday"], "Every day means each day. Everyday is an adjective meaning ordinary."),
  word(upper, "An ____ warm-up is printed on the board.", "everyday", ["every day"], "Everyday is an adjective meaning ordinary and modifies warm-up."),
  word(adv, "The ____ for the solo was a surprise.", "choice", ["choose"], "Choice is the noun. Choose is the verb."),
  word(adv, "You may ____ a partner for the lab.", "choose", ["choice"], "Choose is the verb."),
  word(adv, "Yesterday the editor ____ the headline.", "chose", ["choose"], "Chose is the past tense of choose."),
  word(adv, "Please ____ the guests to their seats.", "lead", ["led"], "Lead is the present-tense verb meaning to guide. The metal lead is a different word."),
  word(adv, "Last year a senior ____ the tour.", "led", ["lead"], "Led is the past tense of lead."),
];

// Homophones and near-homophones from the Commonly Confused Words Glossary
// that were not already in WORDS or MORE_WORDS.
const GLOSSARY_WORDS: WordItem[] = [
  word(all, "Please walk down the center ____ to your seat.", "aisle", ["isle"], "An aisle is a passage between rows. An isle is an island."),
  word(all, "The map marks a small ____ off the coast.", "isle", ["aisle"], "An isle is an island. An aisle is a passage between rows."),
  word(all, "The museum model includes a stone ____.", "altar", ["alter"], "An altar is a raised platform. Alter means to change."),
  word(all, "Do not ____ the results after the trial ends.", "alter", ["altar"], "Alter means to change. An altar is a platform."),
  word(all, "The stage looked ____ before the set arrived.", "bare", ["bear"], "Bare means uncovered. Bear means to carry or endure, or it names the animal."),
  word(all, "The shelf cannot ____ that much weight.", "bear", ["bare"], "Bear means to hold up or endure. Bare means uncovered."),
  word(all, "The story follows a ____ through the woods.", "bear", ["bare"], "Bear names the animal. Bare means uncovered."),
  word(all, "____ branches showed after the windstorm.", "Bare", ["Bear"], "Bare means uncovered. These branches have no leaves."),
  word(all, "Press the ____ before the cart reaches the ramp.", "brake", ["break"], "A brake is a device that stops a vehicle. Break means to smash or fracture."),
  word(all, "A hard fall can ____ the glass slide.", "break", ["brake"], "Break means to smash or fracture. A brake stops a vehicle."),
  word(all, "The wagon's ____ stuck on the hill.", "brake", ["break"], "A brake slows or stops a vehicle."),
  word(all, "Don't ____ the beaker when you rinse it.", "break", ["brake"], "Break means to fracture. A brake is a stopping device."),
  word(all, "We will ____ the tickets at the booth.", "buy", ["by"], "Buy means to purchase. By can mean near or through the action of."),
  word(all, "The mural was painted ____ the art club.", "by", ["buy"], "By means through the action of. Buy means to purchase."),
  word(all, "Please ____ a new notebook before Monday.", "buy", ["by"], "Buy means to purchase."),
  word(all, "Wait ____ the office until the bell rings.", "by", ["buy"], "By means near. Buy means to purchase."),
  word(all, "Oatmeal is a hot ____ served at breakfast.", "cereal", ["serial"], "Cereal is a breakfast food made from grain. Serial means arranged in a series."),
  word(all, "Write the ____ number on the inventory card.", "serial", ["cereal"], "A serial number marks one item in a series. Cereal is a breakfast food."),
  word(all, "The guitarist played one loud ____.", "chord", ["cord"], "A chord is a group of musical notes. A cord is a thin rope or a cable."),
  word(all, "Unplug the ____ before you move the lamp.", "cord", ["chord"], "A cord is a cable or thin rope. A chord is a set of musical notes."),
  word(all, "This sandpaper feels too ____ for the wood.", "coarse", ["course"], "Coarse means rough in texture. A course is a class or a route."),
  word(all, "The biology ____ meets in room 214.", "course", ["coarse"], "A course is a class. Coarse means rough."),
  word(all, "The trail follows the ____ of the creek.", "course", ["coarse"], "A course can be a path or route. Coarse means rough."),
  word(all, "The wool blanket has a ____ weave.", "coarse", ["course"], "Coarse means rough. A course is a class or a path."),
  word(all, "A ____ crossed the trail at dusk.", "deer", ["dear"], "A deer is a hoofed animal. Dear means loved or valued."),
  word(all, "The letter began, \"____ Members of the club.\"", "Dear", ["Deer"], "Dear is a greeting that means valued. A deer is an animal."),
  word(all, "The camera has a ____ lens for close and wide shots.", "dual", ["duel"], "Dual means made of two parts. A duel is a formal fight between two people."),
  word(all, "The history chapter describes a ____ between two rivals.", "duel", ["dual"], "A duel is a formal fight between two people. Dual means consisting of two parts."),
  word(all, "A ____ judge listens to both sides.", "fair", ["fare"], "Fair can mean just. Fare is the price of a ride or the food that is served."),
  word(all, "The spring ____ opens on Saturday morning.", "fair", ["fare"], "A fair can be a festival. Fare is the cost of travel or the food served."),
  word(all, "Bus ____ for students is two dollars.", "fare", ["fair"], "Fare is money paid for travel. Fair means just or names a festival."),
  word(all, "Train ____ is higher on weekends.", "fare", ["fair"], "Fare is the price of a ride. Fair means just or names a festival."),
  word(all, "The backdrop is twelve ____ wide.", "feet", ["feat"], "Feet is the plural of foot. A feat is a skillful achievement."),
  word(all, "Finishing the race in the rain was a real ____.", "feat", ["feet"], "A feat is an achievement that takes skill. Feet is the plural of foot."),
  word(all, "The recipe calls for one cup of ____.", "flour", ["flower"], "Flour is powdered grain used in baking. A flower is the bloom of a plant."),
  word(all, "Label the petals on the diagram of the ____.", "flower", ["flour"], "A flower is part of a plant. Flour is a baking ingredient."),
  word(all, "Dust the pan with ____ so the bread will not stick.", "flour", ["flower"], "Flour is powdered grain. A flower is a bloom."),
  word(all, "The ____ on the windowsill opened overnight.", "flower", ["flour"], "A flower is a bloom. Flour is used in baking."),
  word(all, "This graph is ____ the lab report.", "for", ["four"], "For means intended for. Four is the number 4."),
  word(all, "The quartet needs ____ chairs.", "four", ["for"], "Four is the number 4. For introduces a purpose or a recipient."),
  word(all, "The note is ____ the director.", "for", ["four"], "For points to the person who should receive the note. Four is the number 4."),
  word(all, "We saved ____ seats in the front row.", "four", ["for"], "Four is the number 4."),
  word(all, "____ the cheese for the salad bar.", "Grate", ["Great"], "Grate means to shred. Great means excellent or large."),
  word(all, "That was a ____ opening number.", "great", ["grate"], "Great means excellent. Grate means to shred or names a metal frame."),
  word(all, "Leaves clogged the metal ____ over the drain.", "grate", ["great"], "A grate is a metal frame with openings. Great means excellent or large."),
  word(all, "A ____ deal of planning went into the exhibit.", "great", ["grate"], "Great can mean large in amount. Grate means to shred."),
  word(all, "Can you ____ the cue from the back row?", "hear", ["here"], "Hear means to perceive sound. Here means in this place."),
  word(all, "Set the extra scripts ____ on the table.", "here", ["hear"], "Here means in this place. Hear means to perceive sound."),
  word(all, "I could not ____ the solo over the fan.", "hear", ["here"], "Hear means to perceive a sound."),
  word(all, "____ is the spare microphone.", "Here", ["Hear"], "Here points to this place. Hear means to perceive sound."),
  word(all, "We ____ the bell from the hallway.", "heard", ["herd"], "Heard is the past tense of hear. A herd is a group of animals."),
  word(all, "A ____ of goats blocked the path.", "herd", ["heard"], "A herd is a group of animals. Heard is the past tense of hear."),
  word(all, "The blister is on the ____ of her foot.", "heel", ["heal"], "A heel is the back of the foot. Heal means to become healthy again."),
  word(all, "Rest will help the sprain ____.", "heal", ["heel"], "Heal means to become healthy. A heel is part of the foot."),
  word(all, "Do not ____ the markers in your locker.", "hoard", ["horde"], "Hoard means to hide away or amass. A horde is a large crowd or swarm."),
  word(all, "A ____ of mosquitoes rose from the marsh.", "horde", ["hoard"], "A horde is a swarm or crowd. Hoard means to store things away."),
  word(all, "There is a ____ in the backdrop.", "hole", ["whole"], "A hole is an opening. Whole means entire."),
  word(all, "The ____ class visited the planetarium.", "whole", ["hole"], "Whole means entire. A hole is an opening."),
  word(all, "A ____ in the bucket let the water out.", "hole", ["whole"], "A hole is an opening."),
  word(all, "Read the ____ chapter before the quiz.", "whole", ["hole"], "Whole means entire or complete."),
  word(all, "The story follows a young ____ on a quest.", "knight", ["night"], "A knight is a medieval warrior. Night is the time after sunset."),
  word(all, "The concert is tomorrow ____.", "night", ["knight"], "Night is the period after sunset. A knight is a warrior."),
  word(all, "Tie a firm ____ in the climbing rope.", "knot", ["not"], "A knot is a fastening in rope. Not expresses negation."),
  word(all, "This is ____ the beaker from station two.", "not", ["knot"], "Not expresses negation. A knot is a fastening in rope."),
  word(all, "The sailor's ____ held through the drill.", "knot", ["not"], "A knot is an interlacing of rope."),
  word(all, "Do ____ touch the wet paint on the set.", "not", ["knot"], "Not makes the command negative."),
  word(all, "Do you ____ the formula for density?", "know", ["no"], "Know means to understand. No is a negative word."),
  word(all, "There is ____ spare battery in the drawer.", "no", ["know"], "No expresses negation. Know means to understand."),
  word(all, "I ____ the cue comes after the solo.", "know", ["no"], "Know means to be aware of something."),
  word(all, "____, the lab is closed during lunch.", "No", ["Know"], "No is a negative response. Know means to understand."),
  word(all, "The office sorts the ____ before noon.", "mail", ["male"], "Mail means letters and packages. Male refers to masculine sex or gender."),
  word(all, "In the diagram, the ____ cardinal is bright red.", "male", ["mail"], "Male refers to sex or gender. Mail means letters and packages."),
  word(all, "This chili has no ____.", "meat", ["meet"], "Meat is animal flesh used as food. Meet means to encounter or assemble."),
  word(all, "The clubs ____ in the library after school.", "meet", ["meat"], "Meet means to assemble. Meat is food."),
  word(all, "The recipe lists beans instead of ____.", "meat", ["meet"], "Meat is animal flesh. Meet means to come together."),
  word(all, "Where should the section leaders ____?", "meet", ["meat"], "Meet means to assemble."),
  word(all, "We have ____ microscope left on the cart.", "one", ["won"], "One is the number 1. Won is the past tense of win."),
  word(all, "Our team ____ the debate on Friday.", "won", ["one"], "Won is the past tense of win. One is the number 1."),
  word(all, "____ student still needs a hall pass.", "One", ["Won"], "One is the number. Won is the past tense of win."),
  word(all, "She ____ the spelling bee in eighth grade.", "won", ["one"], "Won is the past tense of win."),
  word(all, "Bring a ____ of goggles to the lab.", "pair", ["pear"], "A pair is a set of two. A pear is a fruit."),
  word(all, "The snack was a sliced ____.", "pear", ["pair"], "A pear is a fruit. A pair is a set of two."),
  word(all, "The library was finally at ____.", "peace", ["piece"], "Peace means calm or freedom from disturbance. A piece is a portion."),
  word(all, "Save me a ____ of poster board.", "piece", ["peace"], "A piece is a portion. Peace means calm."),
  word(all, "The treaty in the story restored ____.", "peace", ["piece"], "Peace means freedom from conflict."),
  word(all, "This ____ of evidence belongs in the report.", "piece", ["peace"], "A piece is a part of a whole."),
  word(all, "Snow covered the mountain ____.", "peak", ["peek"], "A peak is the pointed top of a mountain. A peek is a quick look."),
  word(all, "Don't ____ at the answer key.", "peek", ["peak"], "Peek means to look quickly or secretly. A peak is a summit."),
  word(all, "She wore a ____ blue shirt for the photo.", "plain", ["plane"], "Plain can mean simple. A plane is an airplane or a flat surface."),
  word(all, "Our class boarded the ____ at gate 12.", "plane", ["plain"], "A plane can be an airplane. Plain can mean simple or a flat stretch of land."),
  word(all, "The story is set on a wide, grassy ____.", "plain", ["plane"], "A plain can be a flat area of land. A plane is an airplane or a flat geometric surface."),
  word(all, "In geometry, a ____ has no thickness.", "plane", ["plain"], "A plane can be a flat surface. Plain means simple or names flat land."),
  word(all, "____ the water slowly into the cylinder.", "Pour", ["Pore"], "Pour means to cause liquid to flow. A pore is a tiny opening."),
  word(all, "Each ____ in the sponge lets air through.", "pore", ["pour"], "A pore is a tiny opening. Pour means to cause liquid to flow."),
  word(all, "The ____ moved the picnic into the gym.", "rain", ["reign"], "Rain is water falling from clouds. A reign is a monarch's period of rule."),
  word(all, "The exhibit covers the queen's long ____.", "reign", ["rain"], "A reign is the period when a monarch rules. Rain is precipitation."),
  word(all, "Turn ____ at the library.", "right", ["write"], "Right can mean the opposite of left. Write means to put words on paper."),
  word(all, "Please ____ your name on the folder.", "write", ["right"], "Write means to mark words. Right means correct or the opposite of left."),
  word(all, "That calculation is ____.", "right", ["write"], "Right means correct."),
  word(all, "____ the hypothesis in a complete sentence.", "Write", ["Right"], "Write means to put words on paper."),
  word(all, "Maya has a speaking ____ in the second act.", "role", ["roll"], "A role is a part in a play or a function. Roll means to turn over, or it names a kind of bread."),
  word(all, "Please ____ the cart into the hallway.", "roll", ["role"], "Roll means to move by turning. A role is a part or a job."),
  word(all, "His ____ is to time the light cues.", "role", ["roll"], "A role is a function or a part someone plays."),
  word(all, "The baker shaped the dough into a ____.", "roll", ["role"], "A roll can be a small loaf of bread. A role is a part or a duty."),
  word(all, "The boat lost a ____ in the high wind.", "sail", ["sale"], "A sail is fabric that catches the wind. A sale is an exchange of goods for money."),
  word(all, "The book ____ starts on Monday.", "sale", ["sail"], "A sale is the selling of goods. A sail belongs on a boat."),
  word(all, "The map colors the ____ in blue.", "sea", ["see"], "The sea is a large body of salt water. See means to perceive with the eyes."),
  word(all, "I can ____ the scoreboard from this seat.", "see", ["sea"], "See means to perceive with the eyes. The sea is salt water."),
  word(all, "The ferry crossed a rough ____.", "sea", ["see"], "The sea is an expanse of salt water."),
  word(all, "Did you ____ the comet last night?", "see", ["sea"], "See means to perceive with the eyes."),
  word(all, "She was the ____ volunteer for the early shift.", "sole", ["soul"], "Sole can mean only. Soul means the spiritual part of a person."),
  word(all, "The poem describes the speaker's ____.", "soul", ["sole"], "Soul means the spiritual part of a person. Sole can mean only, or the bottom of a shoe."),
  word(all, "A pebble stuck in the ____ of his shoe.", "sole", ["soul"], "The sole is the bottom of a shoe. The soul is a person's spirit."),
  word(all, "The costume is tight at the ____.", "waist", ["waste"], "The waist is the part of the body above the hips. Waste means to use carelessly, or it means garbage."),
  word(all, "Don't ____ paper on extra copies.", "waste", ["waist"], "Waste means to use carelessly. The waist is part of the body."),
  word(all, "The green bin is for food ____.", "waste", ["waist"], "Waste can mean garbage. The waist is part of the body."),
  word(all, "This is the shortest ____ to the gym.", "way", ["weigh"], "A way is a route or a method. Weigh means to measure how heavy something is."),
  word(all, "____ the sample before you start the trial.", "Weigh", ["Way"], "Weigh means to measure heaviness. A way is a method or a route."),
  word(all, "One ____ to check the result is to repeat the trial.", "way", ["weigh"], "A way can be a method."),
  word(all, "The scale will ____ the fruit for the display.", "weigh", ["way"], "Weigh means to measure heaviness."),
  word(all, "The flashlight beam is too ____.", "weak", ["week"], "Weak means lacking strength. A week is seven days."),
  word(all, "The quiz is next ____.", "week", ["weak"], "A week is seven days. Weak means lacking strength."),
  word(all, "A ____ battery dimmed the meter.", "weak", ["week"], "Weak means lacking strength."),
  word(all, "The club meets twice a ____.", "week", ["weak"], "A week is a period of seven days."),
  word(upper, "____ weather delayed the track meet.", "Adverse", ["Averse"], "Adverse means unfavorable or harmful. Averse means strongly opposed."),
  word(upper, "She is ____ to skipping the warm-up.", "averse", ["adverse"], "Averse means strongly opposed or disliking. Adverse means harmful or unfavorable."),
  word(upper, "The plants suffered ____ effects from the frost.", "adverse", ["averse"], "Adverse means harmful. Averse describes a person's dislike."),
  word(upper, "The speaker did not ____ to the final score.", "allude", ["elude"], "Allude means to mention indirectly. Elude means to escape or avoid."),
  word(upper, "The solution continued to ____ the team.", "elude", ["allude"], "Elude means to escape or evade. Allude means to refer indirectly."),
  word(upper, "The poem seems to ____ to an older myth.", "allude", ["elude"], "Allude means to make an indirect reference."),
  word(upper, "The judges will ____ each science project.", "appraise", ["apprise"], "Appraise means to assess value or quality. Apprise means to inform."),
  word(upper, "Please ____ the director of the schedule change.", "apprise", ["appraise"], "Apprise means to inform someone. Appraise means to judge value or quality."),
  word(upper, "Sit ____ your lab partner.", "beside", ["besides"], "Beside means next to. Besides means in addition or apart from."),
  word(upper, "____, the paint is still wet.", "Besides", ["Beside"], "Besides means in addition. Beside means next to."),
  word(upper, "The trophy case stands ____ the office door.", "beside", ["besides"], "Beside means next to."),
  word(upper, "No one ____ the stage manager has a key.", "besides", ["beside"], "Besides means apart from. Beside means next to."),
  word(upper, "The mural was a ____ between the art classes.", "collaboration", ["corroboration"], "Collaboration means working together. Corroboration is evidence that confirms a statement."),
  word(upper, "A second source provided ____ of the date.", "corroboration", ["collaboration"], "Corroboration is confirming evidence. Collaboration means working together."),
  word(upper, "The report ____ three sections.", "comprises", ["composes"], "Comprise means to consist of. The whole comprises the parts."),
  word(upper, "Three sections ____ the report.", "compose", ["comprise"], "The parts compose the whole. Compose means to make up. Comprise means to consist of."),
  word(upper, "Her ____ kept her from copying the answer.", "conscience", ["conscious"], "Conscience is an inner sense of right and wrong. Conscious means awake or aware."),
  word(upper, "Stay ____ of the time limit during the speech.", "conscious", ["conscience"], "Conscious means aware. Conscience is a sense of right and wrong."),
  word(upper, "A guilty ____ made him return the book.", "conscience", ["conscious"], "Conscience is the inner sense of right and wrong."),
  word(upper, "The ____ hum of the fan never stopped.", "continuous", ["continual"], "Continuous means without any interruption. Continual means repeated often, with short breaks."),
  word(upper, "____ announcements interrupted the rehearsal.", "Continual", ["Continuous"], "Continual means happening repeatedly with pauses. Continuous means without a break."),
  word(upper, "A ____ line of traffic blocked the exit.", "continuous", ["continual"], "Continuous means unbroken."),
  word(upper, "The rubric uses several ____.", "criteria", ["criterion"], "Criteria is the plural of criterion. A criterion is one standard."),
  word(upper, "Clarity is the only ____ on this rubric.", "criterion", ["criteria"], "Criterion is the singular. Criteria is the plural."),
  word(upper, "List every ____ the judges will use.", "criterion", ["criteria"], "The word every calls for the singular criterion. Criteria is the plural."),
  word(upper, "This ____ measures the temperature of the water.", "device", ["devise"], "A device is a tool or piece of equipment. Devise means to plan or invent."),
  word(upper, "The class will ____ a fair rotation for the lab stations.", "devise", ["device"], "Devise means to plan or invent. A device is an object."),
  word(upper, "The timer is a simple ____.", "device", ["devise"], "A device is a piece of equipment."),
  word(upper, "In the novel, the family chose to ____ from their home country.", "emigrate", ["immigrate"], "Emigrate means to leave one's own country. Immigrate means to come into another country to live."),
  word(upper, "The chapter explains why the family decided to ____ to a new country.", "immigrate", ["emigrate"], "Immigrate means to enter a country to live there. Emigrate means to leave one's country."),
  word(upper, "The article explains how the group was ____ for its beliefs.", "persecuted", ["prosecuted"], "Persecute means to mistreat people because of their beliefs or identity. Prosecute means to bring a legal case."),
  word(upper, "The mock trial asks which lawyer will ____ the case.", "prosecute", ["persecute"], "Prosecute means to bring legal proceedings. Persecute means to mistreat someone."),
];

export const confusedWordPatterns: Pattern[] = [
  pattern({
    id: "confused-words",
    difficulties: BAND.all,
    type: "multiple-choice",
    prompt: "Choose the word that correctly completes the sentence.",
    build: (rng, difficulty) => {
      const pool = [...WORDS, ...MORE_WORDS, ...GLOSSARY_WORDS].filter((item) => item.levels.includes(difficulty));
      const item = rng.pick(pool);
      return {
        stimulus: item.stimulus,
        answer: item.answer,
        distractors: item.distractors,
        explanation: item.explanation,
        key: `${item.stimulus}|${item.answer}`,
      };
    },
  }),
];

export const doubleNegativePatterns: Pattern[] = [
  pattern({
    id: "double-negative",
    difficulties: BAND.all,
    type: "rewrite",
    prompt: "Rewrite the sentence so it has only one negative and keeps the same meaning.",
    lines: 1,
    build: (rng) => {
      const name = rng.pick(NAMES);
      const rows = [
        [`${name} doesn't have no pencil.`, `${name} doesn't have a pencil.`, "Doesn't is already negative, so use a instead of no."],
        [`${name} didn't see nobody in the lab.`, `${name} didn't see anybody in the lab.`, "Didn't is negative, so use anybody instead of nobody."],
        [`${name} can't find no goggles.`, `${name} can't find any goggles.`, "Can't is negative, so use any instead of no."],
        [`${name} hasn't never missed a cue.`, `${name} hasn't ever missed a cue.`, "Hasn't is negative, so use ever instead of never."],
        [`${name} won't ask nobody for help.`, `${name} won't ask anybody for help.`, "Won't is negative, so use anybody."],
        [`${name} didn't do nothing wrong.`, `${name} didn't do anything wrong.`, "Didn't is negative, so use anything."],
        ["There isn't no time left.", "There isn't any time left.", "Isn't is negative, so use any."],
        ["The choir couldn't hardly hear the cue.", "The choir could hardly hear the cue.", "Hardly already has a negative meaning, so drop couldn't."],
        [`${name} can't scarcely read the label.`, `${name} can scarcely read the label.`, "Scarcely should not be paired with can't."],
        ["We weren't barely ready.", "We were barely ready.", "Barely should not be paired with a second negative."],
        [`${name} doesn't want nothing from the concession stand.`, `${name} doesn't want anything from the concession stand.`, "Doesn't is negative, so use anything."],
        ["There wasn't nobody at the bus stop.", "There wasn't anybody at the bus stop.", "Wasn't is negative, so use anybody."],
        [`${name} hasn't got no pass.`, `${name} hasn't got a pass.`, "Hasn't is negative, so use a instead of no."],
        ["I can't hardly see the cue from this seat.", "I can hardly see the cue from this seat.", "Use hardly without can't."],
        [`${name} didn't tell nobody the score.`, `${name} didn't tell anybody the score.`, "Didn't is negative, so use anybody."],
        ["The latch won't never stay closed.", "The latch won't ever stay closed.", "Won't is negative, so use ever."],
      ] as const;
      const [stimulus, answer, explanation] = rng.pick(rows);
      return { stimulus, answer, explanation, key: stimulus };
    },
  }),
];

const COMPARE: Array<[string, string, string, string]> = [
  ["Of the two labs, this one is ____.", "brighter", "brightest", "Two things call for the comparative brighter."],
  ["Of the three labs, this one is ____.", "brightest", "brighter", "Three or more call for the superlative brightest."],
  ["This solo is ____ than the first one.", "longer", "longest", "Than signals a comparison of two, so use the comparative longer."],
  ["This is the ____ solo in the concert.", "longest", "longer", "The concert contains more than two solos, so use the superlative."],
  ["Of the two drafts, this thesis is ____.", "clearer", "clearest", "Two drafts call for the comparative."],
  ["Of all the drafts, this thesis is the ____.", "clearest", "clearer", "All the drafts means more than two, so use the superlative."],
  ["This ending is ____ than the earlier one.", "better", "best", "Better is the comparative form of good. It compares two endings."],
  ["This is the ____ ending in the set.", "best", "better", "Best is the superlative form of good."],
  ["Yesterday's rehearsal was ____ than today's.", "worse", "worst", "Worse is the comparative form of bad."],
  ["That was the ____ rehearsal of the week.", "worst", "worse", "Worst is the superlative form of bad."],
  ["The ridge trail is ____ than the creek trail.", "farther", "farthest", "Two trails call for the comparative farther."],
  ["The ridge trail is the ____ of the four routes.", "farthest", "farther", "Four routes call for the superlative farthest."],
  ["Maya has ____ errors than Luis.", "fewer", "fewest", "Two writers call for the comparative fewer."],
  ["Maya has the ____ errors in the class.", "fewest", "fewer", "A whole class is more than two, so use fewest."],
  ["This problem is ____ than the last one.", "harder", "hardest", "Than compares two problems."],
  ["This is the ____ problem on the page.", "hardest", "harder", "The page has more than two problems."],
  ["Of the two paints, this one is ____.", "redder", "reddest", "Two paints call for the comparative."],
  ["Of the five paints, this one is the ____.", "reddest", "redder", "Five items call for the superlative."],
];

export const comparativePatterns: Pattern[] = [
  pattern({
    id: "compare-choice",
    difficulties: BAND.all,
    type: "multiple-choice",
    prompt: "Choose the comparative or superlative form that fits.",
    build: (rng) => {
      const [stimulus, answer, wrong, why] = rng.pick(COMPARE);
      return { stimulus, answer, distractors: [wrong], explanation: why, key: stimulus };
    },
  }),
  revisionPattern("compare-double", BAND.all, "rewrite", "Rewrite the sentence so the comparison is grammatical.", [
    { stimulus: "This draft is more better than the last one.", answer: "This draft is better than the last one.", explanation: "Better is already comparative. Do not add more." },
    { stimulus: "She is the most tallest player on the team.", answer: "She is the tallest player on the team.", explanation: "Tallest is already superlative. Do not add most." },
    { stimulus: "This trail is more steeper than the other one.", answer: "This trail is steeper than the other one.", explanation: "Steeper is already the comparative form." },
    { stimulus: "Of the two solos, this one is the best.", answer: "Of the two solos, this one is better.", explanation: "Use the comparative, better, when exactly two things are compared." },
    { stimulus: "Of the three solos, this one is better.", answer: "Of the three solos, this one is the best.", explanation: "Use the superlative, best, when more than two things are compared." },
    { stimulus: "He is more happier today.", answer: "He is happier today.", explanation: "Happier is already comparative." },
    { stimulus: "That was her most worst performance.", answer: "That was her worst performance.", explanation: "Worst is already superlative." },
    { stimulus: "This beaker is more fuller than that one.", answer: "This beaker is fuller than that one.", explanation: "Fuller is the comparative. Do not add more." },
    { stimulus: "She is the most carefulest editor in the room.", answer: "She is the most careful editor in the room.", explanation: "Careful forms its superlative with most, not with both most and -est." },
    { stimulus: "Of the two plans, this one is the easiest.", answer: "Of the two plans, this one is easier.", explanation: "Two plans call for the comparative easier." },
    { stimulus: "This solution is less clearer than the first.", answer: "This solution is less clear than the first.", explanation: "Less already makes the comparison. Use the positive form clear." },
    { stimulus: "The ridge is the most farthest point on the map.", answer: "The ridge is the farthest point on the map.", explanation: "Farthest is already superlative." },
  ]),
];

const CAPS: Array<[string, string, string]> = [
  ["we visited the lincoln memorial in april.", "We visited the Lincoln Memorial in April.", "Capitalize the first word, the proper noun Lincoln Memorial, and the month April."],
  ["my aunt rosa lives in denver.", "My aunt Rosa lives in Denver.", "Capitalize the first word, the name Rosa, and the city Denver. Do not capitalize aunt when it is not used as a title directly before the name... Actually Aunt Rosa as a name is capitalized when aunt replaces a name. Here 'my aunt Rosa' capitalizes Rosa only in many style guides, but school worksheets often capitalize Aunt when it is part of the name. Use: My Aunt Rosa lives in Denver."],
  ["the science club meets on tuesday.", "The science club meets on Tuesday.", "Capitalize the first word and the day Tuesday. Do not capitalize science when it is a general subject."],
  ["i am taking biology 2 and spanish.", "I am taking Biology 2 and Spanish.", "Capitalize I, the course title Biology 2, and the language Spanish. A numbered course title is capitalized."],
  ["we drove south toward the mississippi river.", "We drove south toward the Mississippi River.", "Do not capitalize south when it is a direction. Capitalize the proper noun Mississippi River."],
  ["she read about the civil war in history class.", "She read about the Civil War in history class.", "Capitalize the historical name Civil War. Do not capitalize the general subject history."],
  ["principal singh announced the spring concert.", "Principal Singh announced the spring concert.", "Capitalize a title directly before a name. Do not capitalize the season spring."],
  ["the principal announced a concert in the spring.", "The principal announced a concert in the spring.", "Do not capitalize principal when it is not used before a name, and do not capitalize the season."],
  ["on memorial day we visited a museum.", "On Memorial Day we visited a museum.", "Capitalize the holiday Memorial Day."],
  ["maya said, \"the beaker cracked.\"", "Maya said, \"The beaker cracked.\"", "Capitalize a name and the first word of a quoted sentence."],
  ["the book the giver is in room 12.", "The book The Giver is in room 12.", "Capitalize the first word and the main words of the book title."],
  ["students from lincoln middle school toured the capitol.", "Students from Lincoln Middle School toured the capitol.", "Capitalize the proper noun Lincoln Middle School. Capitol, the building, is not in this sentence; capitol as a common noun for a building type stays lowercase only if it is not the proper name. This sentence uses capitol as a common noun."],
  ["dear members of the club:", "Dear Members of the Club:", "In a greeting, capitalize the first word and the main words."],
  ["yours truly,", "Yours truly,", "Capitalize the first word of a closing. Do not capitalize truly."],
  ["the rocky mountains are west of here.", "The Rocky Mountains are west of here.", "Capitalize the proper noun Rocky Mountains. Do not capitalize west as a direction."],
  ["we studied jupiter on monday.", "We studied Jupiter on Monday.", "Capitalize the planet and the day."],
  ["coach rahman posted the roster.", "Coach Rahman posted the roster.", "Capitalize the title and the name."],
  ["the coach posted the roster.", "The coach posted the roster.", "Do not capitalize coach when no name follows it."],
  ["our family celebrates thanksgiving in november.", "Our family celebrates Thanksgiving in November.", "Capitalize the holiday and the month."],
  ["i asked, \"where is the spare key?\"", "I asked, \"Where is the spare key?\"", "Capitalize I and the first word of the quoted question."],
  ["the nile river flows north.", "The Nile River flows north.", "Capitalize the proper noun. Do not capitalize the direction north."],
  ["she is taking english, algebra, and art.", "She is taking English, algebra, and art.", "Capitalize the language English. Do not capitalize general subjects such as algebra and art."],
  ["last winter we visited new orleans.", "Last winter we visited New Orleans.", "Capitalize the city. Do not capitalize the season winter."],
  ["the declaration of independence was signed in philadelphia.", "The Declaration of Independence was signed in Philadelphia.", "Capitalize the document and the city."],
  ["please rsvp to ms. alvarez by friday.", "Please RSVP to Ms. Alvarez by Friday.", "Capitalize the abbreviation RSVP, the title Ms., the name, and the day."],
  ["a buddhist temple stands near the park.", "A Buddhist temple stands near the park.", "Capitalize the adjective formed from a religion."],
  ["we hiked in the west for a week.", "We hiked in the West for a week.", "Capitalize West when it names a region rather than a direction."],
  ["turn west at the library.", "Turn west at the library.", "Do not capitalize west when it is a direction. Capitalize the first word."],
];

export const capitalizationPatterns: Pattern[] = [
  revisionPattern(
    "capitalization",
    BAND.all,
    "rewrite",
    "Rewrite the sentence with correct capitalization.",
    CAPS.filter((item) => !item[2].includes("Actually") && !item[2].includes("This sentence uses capitol")).map(
      ([stimulus, answer, explanation]) => ({ stimulus, answer, explanation }),
    ),
  ),
  revisionPattern("capitalization-clean", BAND.all, "rewrite", "Rewrite the sentence with correct capitalization.", [
    { stimulus: "my aunt rosa lives in denver.", answer: "My Aunt Rosa lives in Denver.", explanation: "Capitalize the first word, Aunt when it is part of the name Aunt Rosa, and the city Denver." },
    { stimulus: "students from lincoln middle school toured the state capitol.", answer: "Students from Lincoln Middle School toured the state capitol.", explanation: "Capitalize the school name. The word capitol stays lowercase here because state capitol is not the proper name of one building in this sentence; if a specific building such as the U.S. Capitol were named, it would be capitalized." },
    { stimulus: "the bill of rights protects basic freedoms.", answer: "The Bill of Rights protects basic freedoms.", explanation: "Capitalize the name of the document." },
    { stimulus: "we read about ramadan in world history.", answer: "We read about Ramadan in world history.", explanation: "Capitalize the name of the holiday or observance. Do not capitalize the general subject world history." },
    { stimulus: "senator diaz spoke on labor day.", answer: "Senator Diaz spoke on Labor Day.", explanation: "Capitalize the title before a name and the holiday." },
    { stimulus: "the senator spoke on a holiday.", answer: "The senator spoke on a holiday.", explanation: "Do not capitalize senator when no name follows it." },
    { stimulus: "our address is 14 oak street.", answer: "Our address is 14 Oak Street.", explanation: "Capitalize the parts of a street name." },
    { stimulus: "i love the month of june.", answer: "I love the month of June.", explanation: "Capitalize I and the month." },
  ]),
];

export const numberPatterns: Pattern[] = [
  pattern({
    id: "numbers-small",
    difficulties: BAND.all,
    type: "rewrite",
    prompt: "Rewrite the sentence using the classroom number rules.",
    lines: 1,
    build: (rng) => {
      const rows = [
        ["We need 5 volunteers.", "We need five volunteers.", "Spell out numbers from one through nine."],
        ["There are 3 beakers on the cart.", "There are three beakers on the cart.", "Spell out numbers from one through nine."],
        ["The scene has 8 chairs.", "The scene has eight chairs.", "Spell out eight."],
        ["Bring 2 posters.", "Bring two posters.", "Spell out two."],
        ["We saved 9 folders.", "We saved nine folders.", "Spell out nine."],
        ["The lab has 4 sinks.", "The lab has four sinks.", "Spell out four."],
        ["Order 6 samples.", "Order six samples.", "Spell out six."],
        ["There are 7 maps in the drawer.", "There are seven maps in the drawer.", "Spell out seven."],
        ["There are fifteen beakers on the cart.", "There are 15 beakers on the cart.", "Use numerals for 10 and above."],
        ["The club admitted twelve students.", "The club admitted 12 students.", "Use a numeral for 12 when it does not begin the sentence."],
        ["The choir ordered twenty-five programs.", "The choir ordered 25 programs.", "Use numerals for 10 and above."],
        ["We collected forty cans.", "We collected 40 cans.", "Use a numeral for 40."],
        ["12 students joined the club.", "Twelve students joined the club.", "Spell out a number that begins a sentence."],
        ["15 beakers cracked during the move.", "Fifteen beakers cracked during the move.", "Spell out a number that begins a sentence."],
        ["8 chairs belong in the scene shop.", "Eight chairs belong in the scene shop.", "Spell out a number that begins a sentence, even when it is below ten."],
        ["Meet us at three p.m.", "Meet us at 3:00 p.m.", "Use numerals for times with a.m. or p.m."],
        ["The bus leaves at seven a.m.", "The bus leaves at 7:00 a.m.", "Use a numeral with a.m."],
        ["Rehearsal ends at 4 p.m.", "Rehearsal ends at 4:00 p.m.", "Include minutes when you write a time with p.m."],
      ] as const;
      const [stimulus, answer, explanation] = rng.pick(rows);
      return { stimulus, answer, explanation, key: stimulus };
    },
  }),
  revisionPattern("numbers-abbrev", BAND.all, "rewrite", "Rewrite the sentence so the abbreviations fit formal prose.", [
    { stimulus: "Dr Sanchez will visit rm. 204.", answer: "Dr. Sanchez will visit room 204.", explanation: "Use a period in Dr. Spell out room in formal prose." },
    { stimulus: "The mtg. is in the library.", answer: "The meeting is in the library.", explanation: "Spell out meeting in formal prose." },
    { stimulus: "Ms Alvarez posted the hw.", answer: "Ms. Alvarez posted the homework.", explanation: "Use a period in Ms. and spell out homework." },
    { stimulus: "We need info. about the bus.", answer: "We need information about the bus.", explanation: "Spell out information." },
    { stimulus: "The approx. length is 12 cm.", answer: "The approximate length is 12 cm.", explanation: "Spell out approximate in formal prose. A unit abbreviation such as cm may stay." },
    { stimulus: "Gov Diaz signed the bill.", answer: "Gov. Diaz signed the bill.", explanation: "Use a period in the title abbreviation Gov." },
    { stimulus: "The U.S is sending a delegate.", answer: "The U.S. is sending a delegate.", explanation: "The abbreviation U.S. takes periods." },
    { stimulus: "Pls return the beakers asap.", answer: "Please return the beakers as soon as possible.", explanation: "Spell out texting abbreviations in formal prose." },
    { stimulus: "Prof Kim teaches the lab.", answer: "Prof. Kim teaches the lab.", explanation: "Use a period in the title abbreviation Prof." },
    { stimulus: "The dept. meeting is at noon.", answer: "The department meeting is at noon.", explanation: "Spell out department in formal prose." },
    { stimulus: "We live on Oak St.", answer: "We live on Oak Street.", explanation: "Spell out Street in formal prose." },
    { stimulus: "Jan. is the snowiest month here.", answer: "January is the snowiest month here.", explanation: "Spell out a month when it is not followed by a date." },
  ]),
];

const FORMAL: Array<[string, string, string]> = [
  ["The experiment was a total fail because the kids messed up the measurements.", "The experiment failed because the students recorded the measurements incorrectly.", "Formal writing avoids slang such as total fail and messed up and names the error precisely."],
  ["A lot of kids think the ending is super confusing.", "Many readers find the ending confusing.", "Replace vague, casual wording with a more precise claim."],
  ["The author is kinda saying that memory is unreliable.", "The author suggests that memory is unreliable.", "Kinda saying is too casual for academic writing."],
  ["This source is awesome because it has tons of data.", "This source is useful because it includes extensive data.", "Avoid slang such as awesome and tons of."],
  ["We gotta rerun the trial or the results are gonna be wrong.", "We must rerun the trial, or the results will be inaccurate.", "Gotta and gonna are informal."],
  ["The graph is okay, but the caption is sort of vague.", "The graph is adequate, but the caption is vague.", "Okay and sort of weaken a formal claim."],
  ["In this day and age, kids are always on their phones.", "Students frequently use their phones.", "Replace the cliché and the casual label kids."],
  ["Due to the fact that the bus was late, rehearsal started late.", "Because the bus was late, rehearsal started late.", "Because is more direct than due to the fact that."],
  ["The character is totally obsessed with the river.", "The character is preoccupied with the river.", "Totally obsessed is more casual than the claim needs to be."],
  ["I think the theme is basically freedom.", "The theme is freedom.", "In a formal claim, I think and basically can often be cut."],
  ["The lab got messed up when somebody didn't label stuff.", "The lab procedure failed because the samples were not labeled.", "Name the problem instead of using messed up and stuff."],
  ["This quote really pops because it shows the kid's fear.", "This quotation is effective because it shows the child's fear.", "Pops and kid are informal."],
  ["The results were pretty bad, so we did the experiment over.", "The results were inconclusive, so we repeated the experiment.", "Pretty bad and did over are less precise than inconclusive and repeated."],
  ["At the end of the day, the author wants us to care about the town.", "Ultimately, the author asks readers to care about the town.", "Replace the cliché at the end of the day."],
  ["The article talks about how pollution is a big deal.", "The article explains why pollution is a serious problem.", "Talks about and a big deal are informal."],
  ["You shouldn't just ignore the counterargument.", "Writers should not ignore the counterargument.", "You is conversational here. A formal sentence can address writers in the third person."],
];

export const registerPatterns: Pattern[] = [
  pattern({
    id: "register-rewrite",
    difficulties: BAND.all,
    type: "rewrite",
    prompt: "Rewrite the sentence in a formal academic register. Keep the meaning.",
    lines: 1,
    build: (rng) => {
      const [stimulus, answer, explanation] = rng.pick(FORMAL);
      return {
        stimulus,
        answer,
        explanation: `${explanation} Answers may vary; the key shows one strong revision.`,
        key: stimulus,
      };
    },
  }),
  choicePattern("register-choice", BAND.all, "Which wording is the most formal?", [
    { stimulus: "Choose the most formal way to describe a failed experiment.", answer: "The experiment failed.", distractors: ["The experiment was a total fail.", "The experiment got messed up.", "The experiment was kind of a bust."], explanation: "Failed is direct and formal. The other choices use slang." },
    { stimulus: "Choose the most formal subject.", answer: "the students", distractors: ["the kids", "the guys", "a bunch of people"], explanation: "Students is the appropriate formal noun." },
    { stimulus: "Choose the most formal verb phrase.", answer: "suggests", distractors: ["kinda says", "is basically like", "goes on about"], explanation: "Suggests is precise. The other options are conversational." },
    { stimulus: "Choose the most formal transition.", answer: "because", distractors: ["due to the fact that", "on account of the fact that", "seeing as how"], explanation: "Because is concise and formal." },
    { stimulus: "Choose the most formal evaluation.", answer: "The evidence is insufficient.", distractors: ["The evidence is pretty weak.", "The evidence is not that great.", "The evidence is meh."], explanation: "Insufficient is a formal, precise judgment." },
    { stimulus: "Choose the most formal request.", answer: "Please submit the draft by Friday.", distractors: ["Can you get me the draft by Friday?", "I need that draft ASAP.", "Drop the draft off whenever."], explanation: "The formal request is polite, specific, and free of texting abbreviations." },
    { stimulus: "Choose the most formal claim.", answer: "The narrator is unreliable.", distractors: ["The narrator is super shady.", "The narrator is kind of a liar.", "You can't trust this guy."], explanation: "Unreliable is the literary term and does not rely on slang or you." },
    { stimulus: "Choose the most formal phrase for additional research.", answer: "further research", distractors: ["a lot more digging", "extra stuff to look up", "tons more research"], explanation: "Further research is the standard academic phrase." },
    { stimulus: "Choose the most formal way to cite disagreement.", answer: "Some readers may disagree.", distractors: ["Lots of people won't buy this.", "Not everyone is gonna agree.", "You might think this is wrong."], explanation: "Some readers may disagree is measured and formal." },
    { stimulus: "Choose the most formal closing.", answer: "The evidence supports the claim.", distractors: ["So yeah, the evidence proves it.", "The evidence totally backs this up.", "That's basically the proof."], explanation: "Supports the claim is formal. Proves would also be stronger than the evidence usually allows; supports is the careful choice." },
    { stimulus: "Choose the most formal word for children in a news report.", answer: "children", distractors: ["kids", "kiddos", "little guys"], explanation: "Children is the formal noun." },
    { stimulus: "Choose the most formal revision of gonna.", answer: "will", distractors: ["gonna", "going to" , "about to kinda"], explanation: "Will is the most formal of the choices. Going to is acceptable in semiformal prose, but will is more compact and academic." },
  ]),
];
